### ISSUE TITLE
Support for nullable types

### ISSUE THREAD

**Issue by quarion** [jakubka/swashbuckle-nodatime#1]
Using Web API 2 and Swasbuckle, if I use straight type, eg. LocalTime, then the swagger config is generated correctly.

But nullable types (LocalTime?), are not recognized by this plugin, and are generated like NodaTime types without this plugin installed (the appear as empty objects).

**Comment by jakubka** [comment]
Hey @quarion,

Thanks for opening this issue and yeah, although I do not have the project setup now, you are most probably right.

Would you please open a PR with the fix?

The ConfigureForNodaTime function will need to be extended for nullable types: https://github.com/jakubka/swashbuckle-nodatime/blob/master/src/Swashbuckle.NodaTime/SwaggerDocsConfigExtensions.fs#L23.

Maybe we can use non-generic MapType function which wasn't available before to make the code less spaghetti-like? https://github.com/domaindrivendev/Swashbuckle/blob/fd2a7e9e9f01a3fa1ad4403c5a5d4b6f5c54f0b4/Swashbuckle.Core/Application/SwaggerDocsConfig.cs#L133

Cheers

**Comment by SteveK-GS** [comment]
I submitted a PR in October to add support for nullable types. It's been working here in production for some time but it would be nice to have it in the official Nuget. Would you mind reviewing the PR?

**Comment by jakubka** [comment]
Thanks for that @SteveK-GS! Yes, I will review the PR.

**Comment by jakubka** [comment]
This was done in 2.1.0. Closing the issue
