### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by buvinghausen** [jakubka/swashbuckle-nodatime#12]
I want to use this library but the dependency on .NET Framework full means I cannot run this on Linux or OSX.

**Comment by jakubka** [comment]
Hi @buvinghausen, thanks for raising it up.

Unfortunately I am not able to add support for .NET Core due to other commitments. If you are willing to fork or contribute, I am happy to support you.

Sorry,

J.

**Comment by buvinghausen** [comment]
Done: https://github.com/jakubka/swashbuckle-nodatime/pull/13

**Comment by buvinghausen** [comment]
I'll look into the AppVeyor stuff when I get a chance it's still using msbuild14 which isn't going to work. For now I've got your package hosted to my private artifacts server and will just be pulling it from there.  I should have some more time after InsureTech Connect on 10/4

**Comment by buvinghausen** [comment]
Here's the nuget package hosted on my feed... 
![image](https://user-images.githubusercontent.com/1130210/30777344-62c4e5ec-a086-11e7-8edf-808f0a3243b3.png)

**Comment by buvinghausen** [comment]
I added the overload to invoke Json.NET's default serializer settings since I set them up at the very top of my application thus I don't need to send the settings into the config.  I hope I followed the style and intent you set forth in the project.

If you want to play with the default settings stuff here's my bootstrap code which I now have running with your library on Azure on Linux inside a Docker container.

Cheers

```csharp
JsonConvert.DefaultSettings = () =>
{
	var settings = new JsonSerializerSettings
	{
		ContractResolver = new CamelCasePropertyNamesContractResolver(),
		Converters =
		{
			new StringEnumConverter()
		},
		NullValueHandling = NullValueHandling.Ignore
	};
	settings.ConfigureForNodaTime(DateTimeZoneProviders.Tzdb);
	return settings;
};
```

**Comment by buvinghausen** [comment]
Closing as I've taken on supporting it here: https://github.com/buvinghausen/Swashbuckle.NodaTime.AspNetCore
