### ISSUE TITLE
Swashbuckle dependency

### ISSUE THREAD

**Issue by kkorus** [jakubka/swashbuckle-nodatime#3]
Does swashbuckle-nodatime really need to be dependent on **Swashbuckle** package?  **Swashbuckle.Core** wouldn't be enough?

**Comment by jakubka** [comment]
You might be right. Would you mind raising a PR?

**Comment by SteveK-GS** [comment]
Since I'm working on the solution anyway I don't mind looking at this. I plan to PR shortly.

**Comment by kkorus** [comment]
Awesome, thanks ;)

**Comment by jakubka** [comment]
Done in 2.2.0
