### ISSUE TITLE
swashbuckle-nodatime is not compatible with the latest version of NodaTime

### ISSUE THREAD

**Issue by kevineger** [jakubka/swashbuckle-nodatime#9]
Due to some API changes in the latest version(s) (versions 2+), _swashbuckle-nodatime_ no longer works. I took a shallow look at some of the changes and updating shouldn't bee too difficult. I'd be happy to make the changes but would like to seek guidance on versioning. 

Since the fixes pertain to specific versions of NodaTime (ie: current version of _swashbuckle-nodatime_ is implemented correctly for versions >= `1.3.1` but < `2`, I'd imagine you'd want to keep this repo locked. Should we perhaps consider forking and making a new repo to be used for NodaTime version `2+`?

Again, happy to make the changes - just let me know what you have in mind for versioning to match the correct version of NodaTime.

**Comment by jakubka** [comment]
Hey @kevineger,

Thanks for spotting this and reporting.

We will need to release a new major version of this library. No need to make a fork.

Could you please open a PR with necessary changes?

Please make sure to bump version to 3.0.0.0 [here](https://github.com/jakubka/swashbuckle-nodatime/blob/master/src/Swashbuckle.NodaTime/AssemblyInfo.fs#L26-L27) and add an entry to [CHANGELOG.md](https://github.com/jakubka/swashbuckle-nodatime/blob/master/CHANGELOG.md).

Thank you

**Comment by CodeRevver** [comment]
@jakubka   I made these changes to get everything working for me.  

https://github.com/CodeRevver/swashbuckle-nodatime/tree/3.0.0

**Comment by jakubka** [comment]
Thanks @CodeRevver.

I've moved the code to branch 3.0.0 in this project and created a PR: https://github.com/jakubka/swashbuckle-nodatime/pull/10.

Unfortunately there is a test error on AppVeyor. I will add you as a contributor to the project and would you mind fixing it?

**Comment by jakubka** [comment]
Done in #11
